### PR TITLE
Added a 'Switch lesson' button to the menu.

### PR DESCRIPTION
**Pull request by Tydax**
Hello there,

I added a 'Switch lesson' button to main top menu, because I thought it would be more convenient to have a button instead of having to go into the menu each time you want to switch lesson.

### CODE REVIEW

**Comment by mquinson** [comment]
Excellent, thanks a lot. Could you please specify the license of the image that you are using for the button? We have to track the copyright information on these files too if we want to keep saying that this is a free software ;)

Thanks for this good contribution.

**Comment by Tydax** [comment]
Oh yes, sure, sorry, I forgot about it. The icon is from this URL: http://www.pngfactory.net/png/22629/periodical, so the license used is a Creative Common BY-SA, which means that it requires to name the author, I misread the conditions and thought I could use it freely. So I will take some time tomorrow to look for another icon. My apologies again.

**Comment by mquinson** [comment]
BY-SA is fine. You just have to augment the COPYING file to tell where this icon can be downloaded, and possibly who did it, too. 

If the author's name is expected, I guess that we have to augment that file for all other icon that we have :-/

**Comment by mquinson** [comment]
Could you please augment the COPYING file accordingly so that I can merge your changes please?

Just commit that other change in the same branch and refresh you pull request.

Thanks, Mt

**Comment by Tydax** [comment]
Oh sorry, I forgot to push those changes. I just amended my last commit augmenting the COPYING file with the website where you can find the icon. Thank you.

**Comment by mquinson** [comment]
That's merged now. Thanks for that.

**Pull request merged**
